name: Test-workflow
on: [push]
jobs: 
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: create env file
        run: |
          touch .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      - run: npm install && npm run test

  # test2-job:
  #   environment: dev
  #   env: 
  #     key: ${{ secrets.JWT_SECRET }}
  #     test: ${{ secrets.QA }}
  #     ano: ${{ secrets.DEV }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: echo
  #       run: echo ${{ env.key }} && echo ${{ env.test }} && echo ${{ env.ano }}
